-- FR-09 AC-09-1：欄位對應可儲存為個人範本重複使用。
CREATE TABLE import_mapping_template (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    data_type    VARCHAR(32)  NOT NULL,
    mapping_json JSONB        NOT NULL,
    created_by   BIGINT       NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_import_mapping_template_type
        CHECK (data_type IN ('SALES', 'REVIEW', 'AUDIENCE', 'PRODUCT')),
    CONSTRAINT ck_import_mapping_template_json
        CHECK (jsonb_typeof(mapping_json) = 'object')
);

CREATE UNIQUE INDEX uk_import_mapping_template_owner_name
    ON import_mapping_template (created_by, data_type, lower(name));
CREATE INDEX idx_import_mapping_template_owner_type
    ON import_mapping_template (created_by, data_type, updated_at DESC);

COMMENT ON TABLE import_mapping_template IS
    'FR-09 AC-09-1：使用者可重複套用的欄位對應範本；mapping_json 為來源欄名到系統欄位 key 的物件';

ALTER TABLE import_mapping_template ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ssds_app') THEN
        RAISE NOTICE 'V24：角色 ssds_app 不存在，略過 GRANT 與 policy';
        RETURN;
    END IF;

    GRANT SELECT, INSERT, UPDATE, DELETE ON import_mapping_template TO ssds_app;
    GRANT USAGE, SELECT ON SEQUENCE import_mapping_template_id_seq TO ssds_app;
    CREATE POLICY p_ssds_app_rw ON import_mapping_template
        FOR ALL TO ssds_app USING (true) WITH CHECK (true);
END $$;
