-- §6.7.3：所有 AI 呼叫（包含不經 ai_task 的手動端點與排程）皆須跨重啟保留每日用量。
CREATE TABLE ai_budget_usage_daily (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usage_date      DATE        NOT NULL,
    budget_pool     VARCHAR(16) NOT NULL,
    request_count   INTEGER     NOT NULL DEFAULT 0,
    cache_hit_count INTEGER     NOT NULL DEFAULT 0,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uk_ai_budget_usage_daily_date_pool UNIQUE (usage_date, budget_pool),
    CONSTRAINT ck_ai_budget_usage_daily_pool
        CHECK (budget_pool IN ('TRACK_A', 'TRACK_B', 'RETRY')),
    CONSTRAINT ck_ai_budget_usage_daily_requests CHECK (request_count >= 0),
    CONSTRAINT ck_ai_budget_usage_daily_cache_hits CHECK (cache_hit_count >= 0)
);

COMMENT ON TABLE ai_budget_usage_daily IS
    '§6.7.3 每日 AI 三池用量帳本；是服務重啟還原額度的唯一權威來源';

ALTER TABLE ai_budget_usage_daily ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ssds_app') THEN
        RAISE NOTICE 'V25：角色 ssds_app 不存在，略過 GRANT 與 policy';
        RETURN;
    END IF;

    GRANT SELECT, INSERT, UPDATE ON ai_budget_usage_daily TO ssds_app;
    GRANT USAGE, SELECT ON SEQUENCE ai_budget_usage_daily_id_seq TO ssds_app;
    CREATE POLICY p_ssds_app_rw ON ai_budget_usage_daily
        FOR ALL TO ssds_app USING (true) WITH CHECK (true);
END $$;
