-- hashtag → 品類對照，原本寫死在 ssds-api/config/InstagramHashtagMapping.java，
-- 改落地到資料庫，讓調整追蹤清單不必改 Java 重新編譯部署。
CREATE TABLE instagram_hashtag_mapping (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hashtag     VARCHAR(80) NOT NULL UNIQUE,
    category_id BIGINT      NOT NULL REFERENCES category (id),
    enabled     BOOLEAN     NOT NULL DEFAULT TRUE
);
COMMENT ON TABLE instagram_hashtag_mapping IS
    'Instagram hashtag 熱度採集對照表（原 InstagramHashtagMapping 常數類別）。'
    'InstagramHeatIngestJob 依 enabled=TRUE 的列決定本次要查哪些 hashtag。';
COMMENT ON COLUMN instagram_hashtag_mapping.category_id IS
    '直接用 FK 對到 category，不再用名稱字串比對——查無品類在寫入這張表時就會被擋下，'
    '不必等排程執行才發現對不到、跳過並記警告。';

CREATE INDEX idx_instagram_hashtag_mapping_enabled
    ON instagram_hashtag_mapping (category_id) WHERE enabled = TRUE;

-- 本檔只建 schema，不塞資料：原本兩筆（matcha→零食、低醣→生鮮冷凍）對到的
-- 品類名稱只存在於 db/dev 的假資料（V900），正式 schema 這邊不保證有
-- 同名品類。塞資料的部分移到 db/dev/V910，版本排在 V900 之後，
-- 確保品類先被種出來、FK 才 join 得到（見該檔說明）。

-- V16 定下的規矩：public schema 每一張業務表都要啟用 RLS 並補上
-- ssds_app 的 policy，否則對 ssds_app 而言這張表永遠是空的（查詢
-- 成功但 0 列、INSERT 報 row-level security policy 違反），而且不會有
-- 任何錯誤訊息提醒——這支表原本漏了這段，2026-09-17 的 migration 回歸
-- 測試（MigrationVerificationTest）已經抓到並擋下建置，這裡補上。
-- 做法照 V24（import_mapping_template）的既有模式。
ALTER TABLE instagram_hashtag_mapping ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ssds_app') THEN
        RAISE NOTICE 'V29：角色 ssds_app 不存在，略過 GRANT 與 policy';
        RETURN;
    END IF;

    GRANT SELECT, INSERT, UPDATE, DELETE ON instagram_hashtag_mapping TO ssds_app;
    GRANT USAGE, SELECT ON SEQUENCE instagram_hashtag_mapping_id_seq TO ssds_app;
    CREATE POLICY p_ssds_app_rw ON instagram_hashtag_mapping
        FOR ALL TO ssds_app USING (true) WITH CHECK (true);
END $$;

