package com.example.ssds.api.imports.service;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.example.ssds.infra.dao.*;
import java.nio.file.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.*;
import org.junit.jupiter.api.*;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.transaction.support.TransactionTemplate;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

/** 使用隔離的 PostgreSQL 17.6 容器，不連線到應用程式或共用資料庫。 */
@Testcontainers
class ImportDurabilityDatabaseTest {
    @Container
    static final PostgreSQLContainer<?> postgres =
            new PostgreSQLContainer<>("postgres:17.6-alpine");
    static JdbcTemplate jdbc;
    static DataSourceTransactionManager manager;
    ImportIntegrityDao integrity;
    BulkImportDao bulkImportDao;
    TransactionTemplate tx;
    @BeforeAll static void start() throws Exception {
        var source = new DriverManagerDataSource(
                postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword());
        // 兩個元件必須共用同一個 DataSource，交易資源才能正確綁定。
        jdbc = new JdbcTemplate(source);
        manager = new DataSourceTransactionManager(source);
        jdbc.execute("""
            create table category(id bigint primary key,name text);
            create table import_batch(id bigint primary key,status text,success_rows integer default 0,fail_rows integer default 0);
            create table import_error(batch_id bigint,row_number integer);
            create table product(id bigint generated by default as identity primary key,name text,category_id bigint,
              supplier_id bigint,cost numeric,suggested_price numeric,margin_rate numeric,moq integer,
              season text,status text,track_type text,logistics_condition text,ideal_temp_min numeric,ideal_temp_max numeric,
              shelf_life_days integer,created_by bigint,created_at timestamptz,updated_at timestamptz,deleted_at timestamptz);
            create table sales_record(id bigint generated always as identity primary key,order_date date,product_id bigint,
              product_name_raw text,category_id bigint,price numeric,qty integer check(qty>0),impression integer,audience_code text,import_batch_id bigint);
            create table audience_segment(id bigint generated always as identity primary key,audience_code text unique,name text,price_min numeric,price_max numeric,note text);
            create table category_audience_mix(category_id bigint,audience_id bigint,share numeric check(share>=0 and share<=1),primary key(category_id,audience_id));
            create table test_score(id bigint generated always as identity primary key,product_id bigint);
            """);
        Path migration=Path.of("../ssds-infra/src/main/resources/db/migration/V31__import_integrity_and_recalculation.sql");
        if(!Files.exists(migration)) migration=Path.of("ssds-infra/src/main/resources/db/migration/V31__import_integrity_and_recalculation.sql");
        jdbc.execute(Files.readString(migration));
    }
    @BeforeEach void reset() {
        jdbc.execute("truncate import_recalculation_task,import_sales_identity,import_file_claim,sales_record,category_audience_mix,audience_segment,test_score,product,category,import_batch restart identity cascade");
        jdbc.update("insert into category values(1,'零食'),(2,'飲料')");
        jdbc.update("insert into product(id,name,category_id) values(1,'奶茶',1)");
        jdbc.update("insert into import_batch(id,status) values(1,'FAILED'),(2,'SUCCEEDED')");
        integrity=new ImportIntegrityDao(jdbc);
        bulkImportDao=new BulkImportDao(jdbc,mock(ApplicationEventPublisher.class));
        tx=new TransactionTemplate(manager);
    }
    @Test void salesIdentityAndQueueRollBackWithBusinessData() {
        String key="a".repeat(64),payload="b".repeat(64);
        assertThatThrownBy(()->tx.executeWithoutResult(status->{
            integrity.reserveSales(1L,Map.of(key,payload));
            bulkImportDao.batchInsertSalesRecords(List.of(new BulkImportDao.SalesRow(LocalDate.now(),1L,"奶茶",1L,BigDecimal.TEN,2,null,null,1L)));
            integrity.enqueue(1L,List.of(1L));
            throw new IllegalStateException("simulate commit failure");
        })).isInstanceOf(IllegalStateException.class);
        assertThat(count("sales_record")).isZero();assertThat(count("import_sales_identity")).isZero();assertThat(count("import_recalculation_task")).isZero();
        tx.executeWithoutResult(status->integrity.reserveSale(1L,key,payload));
        assertThatThrownBy(()->tx.executeWithoutResult(status->integrity.reserveSale(2L,key,payload)))
            .isInstanceOf(ImportIntegrityDao.DuplicateSaleException.class);
        assertThatThrownBy(()->tx.executeWithoutResult(status->integrity.reserveSale(2L,key,"c".repeat(64))))
            .isInstanceOf(ImportIntegrityDao.ConflictingSaleException.class);
    }
    @Test void sameFileCannotBeClaimedAfterPartialCommitButCanAfterZeroWrites() {
        String hash="f".repeat(64);
        tx.executeWithoutResult(status->integrity.claimFile(1L,hash));
        jdbc.update("update import_batch set success_rows=1 where id=1");
        assertThatThrownBy(()->tx.executeWithoutResult(status->integrity.claimFile(2L,hash))).isInstanceOf(IllegalArgumentException.class);
        jdbc.update("update import_batch set success_rows=0 where id=1");
        tx.executeWithoutResult(status->integrity.claimFile(2L,hash));
        assertThat(jdbc.queryForObject("select batch_id from import_file_claim",Long.class)).isEqualTo(2L);
    }
    @Test void failedImportStillRecalculatesAndScoreAndCompletionAreAtomicAcrossRestart() {
        integrity.enqueue(1L,List.of(1L));
        var item=mock(ImportScoreRecalculationItemService.class);
        when(item.recalculate(1L)).thenAnswer(invocation->{jdbc.update("insert into test_score(product_id) values(1)");throw new IllegalStateException("after snapshot");});
        var worker=new ImportScoreRecalculationService(jdbc,item,manager);
        assertThat(worker.processOne(1L)).isTrue();
        assertThat(count("test_score")).isZero();
        assertThat(jdbc.queryForObject("select attempts from import_recalculation_task",Integer.class)).isEqualTo(1);
        jdbc.update("update import_recalculation_task set next_attempt_at=now()");
        org.mockito.Mockito.reset(item);
        when(item.recalculate(1L)).thenAnswer(invocation->{jdbc.update("insert into test_score(product_id) values(1)");return ImportScoreRecalculationItemService.Result.SCORED;});
        var restarted=new ImportScoreRecalculationService(jdbc,item,manager);
        assertThat(restarted.processOne(null)).isTrue();assertThat(restarted.processOne(null)).isFalse();
        assertThat(count("test_score")).isEqualTo(1);
        assertThat(integrity.recalculationSummary(1L)).containsEntry("SCORED",1);
    }
    @Test void retriesStopAfterThreeFailuresAndCanBeExplicitlyRestarted() {
        integrity.enqueue(1L,List.of(1L));
        var item=mock(ImportScoreRecalculationItemService.class);
        when(item.recalculate(1L)).thenThrow(new IllegalStateException("offline"));
        var worker=new ImportScoreRecalculationService(jdbc,item,manager);
        for(int i=0;i<3;i++){jdbc.update("update import_recalculation_task set next_attempt_at=now()");assertThat(worker.processOne(null)).isTrue();}
        assertThat(worker.processOne(null)).isFalse();
        assertThat(integrity.recalculationSummary(1L)).containsEntry("FAILED",1);
        assertThat(integrity.retry(1L)).isEqualTo(1);
        assertThat(jdbc.queryForObject("select attempts from import_recalculation_task",Integer.class)).isZero();
    }
    @Test void productInsertCreatesDurableTaskInTheSameStatement() {
        // Explicit fixture ID must not collide with the generated identity.
        jdbc.execute("alter table product alter column id restart with 2");
        var row=new BulkImportDao.ProductRow("新商品",1L,null,BigDecimal.ONE,BigDecimal.TEN,new BigDecimal("0.9"),1,"ALL","A",null,null,null,null,null);
        tx.executeWithoutResult(status->assertThat(bulkImportDao.batchInsertProducts(List.of(row),1L)).isEqualTo(1));
        assertThat(count("import_recalculation_task")).isEqualTo(1);
    }
    @Test void audienceReferencesCanBeReusedAndReplacementRollsBackAsAUnit() {
        var dao=bulkImportDao;
        var main=new BulkImportDao.AudienceRow("MAIN","主力",BigDecimal.ZERO,BigDecimal.TEN,null,false);
        tx.executeWithoutResult(status->{
            integrity.lockAudienceImport();assertThat(dao.batchInsertAudiences(List.of(main,main))).isEqualTo(2);
            dao.batchUpsertAudienceMix(List.of(new BulkImportDao.AudienceMixRow(1L,1L,BigDecimal.ONE)));
        });
        assertThat(count("audience_segment")).isEqualTo(1);
        assertThatThrownBy(()->tx.executeWithoutResult(status->{
            integrity.clearMix(1L);
            dao.batchUpsertAudienceMix(List.of(new BulkImportDao.AudienceMixRow(1L,1L,new BigDecimal("0.7"))));
            throw new IllegalStateException("second row failed");
        })).isInstanceOf(IllegalStateException.class);
        assertThat(jdbc.queryForObject("select share from category_audience_mix",BigDecimal.class)).isEqualByComparingTo("1");
        var update=new BulkImportDao.AudienceRow("MAIN","主力",BigDecimal.ZERO,new BigDecimal("20"),null,true);
        tx.executeWithoutResult(status->{dao.batchInsertAudiences(List.of(update));integrity.enqueueAudience(1L,List.of("MAIN"),List.of());});
        assertThat(integrity.recalculationSummary(1L)).containsEntry("PENDING",1);
    }
    @Test void competingWorkersCannotCreateTwoScoresForOneTask() throws Exception {
        integrity.enqueue(1L,List.of(1L));
        var entered=new java.util.concurrent.CountDownLatch(1);
        var release=new java.util.concurrent.CountDownLatch(1);
        var item=mock(ImportScoreRecalculationItemService.class);
        when(item.recalculate(1L)).thenAnswer(invocation->{
            entered.countDown();
            if(!release.await(5,java.util.concurrent.TimeUnit.SECONDS)) throw new IllegalStateException("test worker timed out");
            jdbc.update("insert into test_score(product_id) values(1)");
            return ImportScoreRecalculationItemService.Result.SCORED;
        });
        var first=new ImportScoreRecalculationService(jdbc,item,manager);
        var second=new ImportScoreRecalculationService(jdbc,item,manager);
        try(var pool=java.util.concurrent.Executors.newSingleThreadExecutor()) {
            var running=pool.submit(()->first.processOne(null));
            try {
                assertThat(entered.await(5,java.util.concurrent.TimeUnit.SECONDS)).isTrue();
                assertThat(second.processOne(null)).isFalse();
            } finally {release.countDown();}
            assertThat(running.get(5,java.util.concurrent.TimeUnit.SECONDS)).isTrue();
        }
        assertThat(count("test_score")).isEqualTo(1);
        assertThat(second.processOne(null)).isFalse();
    }
    private int count(String table){return jdbc.queryForObject("select count(*) from "+table,Integer.class);}
}
